server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.uuid}

spring:
  profiles:
    active: dev
#
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: rabbitmq
#    password: passw0rd


management:
  endpoints:
    web:
      exposure:
        include: "*"